name: First workFlow  # Name your workFlow

# next after giving name, when this workflow should be executed

on: workflow_dispatch # on is the reserved word, and workflow_dispatch is an event and it make sure to manually trigger by the user

jobs: # reserved word
  first-job:
    runs-on: ubuntu-latest # runs on is the runner, basically machine that will run your code
    steps: # consists of list of steps and is reserved word
      - name: Print greeting
        run: echo "welcome to github actions"
      - name: 
        run: echp "Done - bye"

